### PR TITLE
Alloy Furnace Texture 1.1

### PR DESCRIPTION
**Pull request by Nexonus**
alloyfurnaceactive
alloyfurnacebottom
alloyfurnaceinactive
alloyfurnaceside
alloyfurnaceside2
alloyfurnacetop
I hope that I did not mess it up now.

### CODE REVIEW

**Comment by Davoleo** [comment]
mmh, you compared the wrong branches

**Comment by Davoleo** [comment]
you need to compare dav-branch to dav-branch for the tile entity textures @Nexonus

**Comment by Davoleo** [comment]
Will be re-opened when the correct branch is compared

**Comment by Nexonus** [comment]
Alright, uh how can I change "From 1.12.2" to "Dav-branch"?

**Comment by Davoleo** [comment]
there's an edit button on the top-right

**Comment by Nexonus** [comment]
Yeah I see it, but upon pressing I can only change the name, and set the target branch. I cannot modify the source one.

**Comment by Davoleo** [comment]
oof, try making a new one, comparing across forks this time :P

**Comment by Davoleo** [comment]
@Nexonus  ^

**Pull request closed without merging**
